# Generated by Django 3.2.7 on 2021-09-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('fileseq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.fileseq', verbose_name='Файлы')),
                ('docno', models.CharField(db_index=True, max_length=32, verbose_name='Номер договора')),
                ('docdate', models.DateField(db_index=True, verbose_name='Дата договора')),
                ('docsum', models.DecimalField(db_index=True, decimal_places=2, max_digits=11, null=True, verbose_name='Сумма договора')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ДатаВремя')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Камменты')),
            ],
            options={
                'verbose_name': 'Резолюция',
                'verbose_name_plural': 'Резолюции',
                'ordering': ('ctime',),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(db_index=True, default=False, verbose_name='Согласовано')),
            ],
            options={
                'verbose_name': 'Подписант',
                'verbose_name_plural': 'Подписанты',
                'ordering': ('contract',),
            },
        ),
    ]
