# Generated by Django 3.2.7 on 2021-09-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('contract', '0001_initial'),
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='approve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contrib.approver', verbose_name='Подписант'),
        ),
        migrations.AddField(
            model_name='route',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='route',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contrib.role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='event',
            name='approve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contrib.approver', verbose_name='Подписант'),
        ),
        migrations.AddField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='contract',
            name='assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_contracts', to='contrib.approver', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contracts', to='contrib.customer', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='contract',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_contracts', to='contrib.department', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_contracts', to='contrib.payer', verbose_name='Наша фирма'),
        ),
        migrations.AddField(
            model_name='contract',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_contracts', to='contrib.place', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='contract',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_contracts', to='core.org', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_contracts', to='contrib.state', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_contracts', to='contrib.subject', verbose_name='ПодОбъект'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('contract', 'role')},
        ),
    ]
