INSERT INTO "clients_positions" VALUES(1,'Главный врач (президент, директор, заведующий, начальник, управляющий)','0.1');
INSERT INTO "clients_positions" VALUES(2,'Директор больницы (дома) сестринского ухода, хосписа','0.1');
INSERT INTO "clients_positions" VALUES(3,'Директор (заведующий) аптечной организации','0.1');
INSERT INTO "clients_positions" VALUES(4,'Заведующий медицинским складом мобилизационного резерва','0.1');
INSERT INTO "clients_positions" VALUES(5,'Заведующий молочной кухней','0.1');
INSERT INTO "clients_positions" VALUES(6,'Заместитель руководителя (главного врача, директора, заведующего, начальника, управляющего)','0.1');
INSERT INTO "clients_positions" VALUES(7,'Главная медицинская сестра, главная акушерка, главный фельдшер','0.1');
INSERT INTO "clients_positions" VALUES(8,'Руководитель (главный врач, директор, начальник) федерального бюджетного учреждения Федеральной службы по надзору в сфере защиты прав потребителей и благополучия человека и Федерального медико-биологического агентства','0.1');
INSERT INTO "clients_positions" VALUES(9,'Заведующий','0.2');
INSERT INTO "clients_positions" VALUES(10,'Начальник','0.2');
INSERT INTO "clients_positions" VALUES(11,'врач-стажер','3.1');
INSERT INTO "clients_positions" VALUES(12,'врач по авиационной и космической медицине','3.1');
INSERT INTO "clients_positions" VALUES(13,'врач-акушер-гинеколог','3.1');
INSERT INTO "clients_positions" VALUES(14,'врач-акушер-гинеколог цехового врачебного участка','3.1');
INSERT INTO "clients_positions" VALUES(15,'врач-аллерголог-иммунолог','3.1');
INSERT INTO "clients_positions" VALUES(16,'врач-анестезиолог-реаниматолог','3.1');
INSERT INTO "clients_positions" VALUES(17,'врач-бактериолог','3.1');
INSERT INTO "clients_positions" VALUES(18,'врач-вирусолог','3.1');
INSERT INTO "clients_positions" VALUES(19,'врач-гастроэнтеролог','3.1');
INSERT INTO "clients_positions" VALUES(20,'врач-гематолог','3.1');
INSERT INTO "clients_positions" VALUES(21,'врач-генетик','3.1');
INSERT INTO "clients_positions" VALUES(22,'врач-гериатр','3.1');
INSERT INTO "clients_positions" VALUES(23,'врач-дезинфектолог','3.1');
INSERT INTO "clients_positions" VALUES(24,'врач-дерматовенеролог','3.1');
INSERT INTO "clients_positions" VALUES(25,'врач-детский кардиолог','3.1');
INSERT INTO "clients_positions" VALUES(26,'врач-детский онколог','3.1');
INSERT INTO "clients_positions" VALUES(27,'врач-детский уролог-андролог','3.1');
INSERT INTO "clients_positions" VALUES(28,'врач-детский хирург','3.1');
INSERT INTO "clients_positions" VALUES(29,'врач-детский эндокринолог','3.1');
INSERT INTO "clients_positions" VALUES(30,'врач-диабетолог','3.1');
INSERT INTO "clients_positions" VALUES(31,'врач-диетолог','3.1');
INSERT INTO "clients_positions" VALUES(32,'врач здравпункта','3.1');
INSERT INTO "clients_positions" VALUES(33,'врач-инфекционист','3.1');
INSERT INTO "clients_positions" VALUES(34,'врач-кардиолог','3.1');
INSERT INTO "clients_positions" VALUES(35,'врач клинической лабораторной диагностики','3.1');
INSERT INTO "clients_positions" VALUES(36,'врач-клинический миколог','3.1');
INSERT INTO "clients_positions" VALUES(37,'врач-клинический фармаколог','3.1');
INSERT INTO "clients_positions" VALUES(38,'врач-колопроктолог','3.1');
INSERT INTO "clients_positions" VALUES(39,'врач-косметолог','3.1');
INSERT INTO "clients_positions" VALUES(40,'врач-лабораторный генетик','3.1');
INSERT INTO "clients_positions" VALUES(41,'врач-лабораторный миколог','3.1');
INSERT INTO "clients_positions" VALUES(42,'врач мануальной терапии','3.1');
INSERT INTO "clients_positions" VALUES(43,'врач-методист','3.1');
INSERT INTO "clients_positions" VALUES(44,'врач-невролог','3.1');
INSERT INTO "clients_positions" VALUES(45,'врач-нейрохирург','3.1');
INSERT INTO "clients_positions" VALUES(46,'врач-неонатолог','3.1');
INSERT INTO "clients_positions" VALUES(47,'врач-нефролог','3.1');
INSERT INTO "clients_positions" VALUES(48,'врач общей практики (семейный врач)','3.1');
INSERT INTO "clients_positions" VALUES(49,'врач-онколог','3.1');
INSERT INTO "clients_positions" VALUES(50,'врач-ортодонт','3.1');
INSERT INTO "clients_positions" VALUES(51,'врач-оториноларинголог','3.1');
INSERT INTO "clients_positions" VALUES(52,'','3.1');
INSERT INTO "clients_positions" VALUES(53,'врач-офтальмолог','3.1');
INSERT INTO "clients_positions" VALUES(54,'врач-офтальмолог-протезист','3.1');
INSERT INTO "clients_positions" VALUES(55,'врач-паразитолог','3.1');
INSERT INTO "clients_positions" VALUES(56,'врач-патологоанатом','3.1');
INSERT INTO "clients_positions" VALUES(57,'врач-педиатр','3.1');
INSERT INTO "clients_positions" VALUES(58,'врач-педиатр городской (районный)','3.1');
INSERT INTO "clients_positions" VALUES(59,'врач-педиатр участковый','3.1');
INSERT INTO "clients_positions" VALUES(60,'врач-пластический хирург','3.1');
INSERT INTO "clients_positions" VALUES(61,'врач по водолазной медицине','3.1');
INSERT INTO "clients_positions" VALUES(62,'врач по гигиене детей и подростков','3.1');
INSERT INTO "clients_positions" VALUES(63,'врач по гигиене питания','3.1');
INSERT INTO "clients_positions" VALUES(64,'врач по гигиене труда','3.1');
INSERT INTO "clients_positions" VALUES(65,'врач по гигиеническому воспитанию','3.1');
INSERT INTO "clients_positions" VALUES(66,'врач по коммунальной гигиене','3.1');
INSERT INTO "clients_positions" VALUES(67,'врач по санаторно-курортному лечению','3.1');
INSERT INTO "clients_positions" VALUES(68,'врач по лечебной физкультуре','3.1');
INSERT INTO "clients_positions" VALUES(69,'врач по медико-социальной экспертизе','3.1');
INSERT INTO "clients_positions" VALUES(70,'врач по медицинской реабилитации','3.1');
INSERT INTO "clients_positions" VALUES(71,'врач по медицинской профилактике','3.1');
INSERT INTO "clients_positions" VALUES(72,'врач по общей гигиене','3.1');
INSERT INTO "clients_positions" VALUES(73,'врач по радиационной гигиене','3.1');
INSERT INTO "clients_positions" VALUES(74,'врач по рентгенэндоваскулярным диагностике и лечению','3.1');
INSERT INTO "clients_positions" VALUES(75,'врач по санитарно-гигиеническим лабораторным исследованиям','3.1');
INSERT INTO "clients_positions" VALUES(76,'врач по спортивной медицине','3.1');
INSERT INTO "clients_positions" VALUES(77,'врач приемного отделения','3.1');
INSERT INTO "clients_positions" VALUES(78,'врач-профпатолог','3.1');
INSERT INTO "clients_positions" VALUES(79,'врач-психиатр','3.1');
INSERT INTO "clients_positions" VALUES(80,'врач-психиатр участковый','3.1');
INSERT INTO "clients_positions" VALUES(81,'врач-психиатр детский','3.1');
INSERT INTO "clients_positions" VALUES(82,'врач-психиатр детский участковый','3.1');
INSERT INTO "clients_positions" VALUES(83,'врач-психиатр подростковый','3.1');
INSERT INTO "clients_positions" VALUES(84,'врач-психиатр подростковый участковый','3.1');
INSERT INTO "clients_positions" VALUES(85,'врач-психиатр-нарколог','3.1');
INSERT INTO "clients_positions" VALUES(86,'врач-психиатр-нарколог участковый','3.1');
INSERT INTO "clients_positions" VALUES(87,'врач-психотерапевт','3.1');
INSERT INTO "clients_positions" VALUES(88,'врач-пульмонолог','3.1');
INSERT INTO "clients_positions" VALUES(89,'врач-радиолог','3.1');
INSERT INTO "clients_positions" VALUES(90,'врач-радиотерапевт','3.1');
INSERT INTO "clients_positions" VALUES(91,'врач-ревматолог','3.1');
INSERT INTO "clients_positions" VALUES(92,'врач-рентгенолог','3.1');
INSERT INTO "clients_positions" VALUES(93,'врач-рефлексотерапевт','3.1');
INSERT INTO "clients_positions" VALUES(94,'врач-сексолог','3.1');
INSERT INTO "clients_positions" VALUES(95,'врач-сердечно-сосудистый хирург','3.1');
INSERT INTO "clients_positions" VALUES(96,'врач скорой медицинской помощи','3.1');
INSERT INTO "clients_positions" VALUES(97,'врач-статистик','3.1');
INSERT INTO "clients_positions" VALUES(98,'врач-стоматолог','3.1');
INSERT INTO "clients_positions" VALUES(99,'врач-стоматолог детский','3.1');
INSERT INTO "clients_positions" VALUES(100,'врач-стоматолог-ортопед','3.1');
INSERT INTO "clients_positions" VALUES(101,'врач-стоматолог-терапевт','3.1');
INSERT INTO "clients_positions" VALUES(102,'врач-стоматолог-хирург','3.1');
INSERT INTO "clients_positions" VALUES(103,'врач-судебно-медицинский эксперт','3.1');
INSERT INTO "clients_positions" VALUES(104,'врач-судебно-психиатрический эксперт','3.1');
INSERT INTO "clients_positions" VALUES(105,'врач-сурдолог-оториноларинголог','3.1');
INSERT INTO "clients_positions" VALUES(106,'врач-сурдолог-протезист','3.1');
INSERT INTO "clients_positions" VALUES(107,'врач-терапевт','3.1');
INSERT INTO "clients_positions" VALUES(108,'врач-терапевт подростковый','3.1');
INSERT INTO "clients_positions" VALUES(109,'врач-терапевт участковый','3.1');
INSERT INTO "clients_positions" VALUES(110,'врач-терапевт участковый цехового врачебного участка','3.1');
INSERT INTO "clients_positions" VALUES(111,'врач-токсиколог','3.1');
INSERT INTO "clients_positions" VALUES(112,'врач-торакальный хирург','3.1');
INSERT INTO "clients_positions" VALUES(113,'врач-травматолог-ортопед','3.1');
INSERT INTO "clients_positions" VALUES(114,'врач-трансфузиолог','3.1');
INSERT INTO "clients_positions" VALUES(115,'врач ультразвуковой диагностики','3.1');
INSERT INTO "clients_positions" VALUES(116,'врач-уролог','3.1');
INSERT INTO "clients_positions" VALUES(117,'врач-физиотерапевт','3.1');
INSERT INTO "clients_positions" VALUES(118,'врач-фтизиатр','3.1');
INSERT INTO "clients_positions" VALUES(119,'врач-фтизиатр участковый','3.1');
INSERT INTO "clients_positions" VALUES(120,'врач функциональной диагностики','3.1');
INSERT INTO "clients_positions" VALUES(121,'врач-хирург','3.1');
INSERT INTO "clients_positions" VALUES(122,'врач-челюстно-лицевой хирург','3.1');
INSERT INTO "clients_positions" VALUES(123,'врач-эндокринолог','3.1');
INSERT INTO "clients_positions" VALUES(124,'врач-эндоскопист','3.1');
INSERT INTO "clients_positions" VALUES(125,'врач-эпидемиолог','3.1');
INSERT INTO "clients_positions" VALUES(126,'старший врач станции (отделения) скорой медицинской помощи','3.1');
INSERT INTO "clients_positions" VALUES(127,'старший врач станции (отделения) скорой медицинской помощи горноспасательных частей','3.1');
INSERT INTO "clients_positions" VALUES(128,'судовой врач','3.1');
INSERT INTO "clients_positions" VALUES(129,'провизор-стажер','3.2');
INSERT INTO "clients_positions" VALUES(130,'провизор-аналитик','3.2');
INSERT INTO "clients_positions" VALUES(131,'провизор-технолог','3.2');
INSERT INTO "clients_positions" VALUES(132,'старший провизор','3.2');
INSERT INTO "clients_positions" VALUES(133,'заведующий фельдшерско-акушерским пунктом - фельдшер (акушерка, медицинская сестра)','3.3');
INSERT INTO "clients_positions" VALUES(134,'заведующий здравпунктом - фельдшер (медицинская сестра)','3.3');
INSERT INTO "clients_positions" VALUES(135,'заведующий производством учреждений (отделов, отделений, лабораторий) зубопротезирования','3.3');
INSERT INTO "clients_positions" VALUES(136,'зубной врач','3.3');
INSERT INTO "clients_positions" VALUES(137,'старшая медицинская сестра (акушерка, фельдшер, операционная медицинская сестра, зубной техник)','3.3');
INSERT INTO "clients_positions" VALUES(138,'фельдшер','3.3');
INSERT INTO "clients_positions" VALUES(139,'фельдшер скорой медицинской помощи','3.3');
INSERT INTO "clients_positions" VALUES(140,'фельдшер-водитель скорой медицинской помощи','3.3');
INSERT INTO "clients_positions" VALUES(141,'фельдшер-лаборант (медицинский лабораторный техник)','3.3');
INSERT INTO "clients_positions" VALUES(142,'фельдшер-нарколог','3.3');
INSERT INTO "clients_positions" VALUES(143,'фельдшер по приему вызовов скорой медицинской помощи и передаче их выездным бригадам скорой медицинской помощи','3.3');
INSERT INTO "clients_positions" VALUES(144,'акушер','3.3');
INSERT INTO "clients_positions" VALUES(145,'гигиенист стоматологический','3.3');
INSERT INTO "clients_positions" VALUES(146,'зубной техник','3.3');
INSERT INTO "clients_positions" VALUES(147,'инструктор-дезинфектор','3.3');
INSERT INTO "clients_positions" VALUES(148,'инструктор по гигиеническому воспитанию','3.3');
INSERT INTO "clients_positions" VALUES(149,'инструктор по лечебной физкультуре','3.3');
INSERT INTO "clients_positions" VALUES(150,'лаборант','3.3');
INSERT INTO "clients_positions" VALUES(151,'медицинская сестра','3.3');
INSERT INTO "clients_positions" VALUES(152,'медицинская сестра-анестезист','3.3');
INSERT INTO "clients_positions" VALUES(153,'медицинская сестра врача общей практики (семейного врача)','3.3');
INSERT INTO "clients_positions" VALUES(154,'медицинская сестра диетическая','3.3');
INSERT INTO "clients_positions" VALUES(155,'медицинская сестра медико-социальной помощи','3.3');
INSERT INTO "clients_positions" VALUES(156,'медицинская сестра палатная (постовая)','3.3');
INSERT INTO "clients_positions" VALUES(157,'медицинская сестра патронажная','3.3');
INSERT INTO "clients_positions" VALUES(158,'медицинская сестра перевязочной','3.3');
INSERT INTO "clients_positions" VALUES(159,'медицинская сестра по косметологии','3.3');
INSERT INTO "clients_positions" VALUES(160,'медицинская сестра по массажу','3.3');
INSERT INTO "clients_positions" VALUES(161,'медицинская сестра по приему вызовов скорой медицинской помощи и передаче их выездным бригадам скорой медицинской помощи','3.3');
INSERT INTO "clients_positions" VALUES(162,'медицинская сестра по физиотерапии','3.3');
INSERT INTO "clients_positions" VALUES(163,'медицинская сестра по реабилитации','3.3');
INSERT INTO "clients_positions" VALUES(164,'медицинская сестра приемного отделения','3.3');
INSERT INTO "clients_positions" VALUES(165,'медицинская сестра процедурной','3.3');
INSERT INTO "clients_positions" VALUES(166,'медицинская сестра стерилизационной','3.3');
INSERT INTO "clients_positions" VALUES(167,'медицинская сестра участковая','3.3');
INSERT INTO "clients_positions" VALUES(168,'медицинский дезинфектор','3.3');
INSERT INTO "clients_positions" VALUES(169,'медицинский лабораторный техник','3.3');
INSERT INTO "clients_positions" VALUES(170,'медицинский оптик-оптометрист','3.3');
INSERT INTO "clients_positions" VALUES(171,'медицинский регистратор','3.3');
INSERT INTO "clients_positions" VALUES(172,'медицинский статистик','3.3');
INSERT INTO "clients_positions" VALUES(173,'медицинский технолог','3.3');
INSERT INTO "clients_positions" VALUES(174,'операционная медицинская сестра','3.3');
INSERT INTO "clients_positions" VALUES(175,'помощник (врача-паразитолога, врача по гигиене детей и подростков, врача по гигиене питания, врача по гигиеническому воспитанию, врача по гигиене труда, врача по коммунальной гигиене, врача по общей гигиене, врача по радиационной гигиене, врача-эпидемиолога)','3.3');
INSERT INTO "clients_positions" VALUES(176,'помощник энтомолога','3.3');
INSERT INTO "clients_positions" VALUES(177,'рентгенолаборант','3.3');
INSERT INTO "clients_positions" VALUES(178,'старший фармацевт','3.4');
INSERT INTO "clients_positions" VALUES(179,'фармацевт','3.4');
INSERT INTO "clients_positions" VALUES(180,'младшая медицинская сестра по уходу за больными','3.5');
INSERT INTO "clients_positions" VALUES(181,'санитар','3.5');
INSERT INTO "clients_positions" VALUES(182,'санитар-водитель','3.5');
INSERT INTO "clients_positions" VALUES(183,'сестра-хозяйка','3.5');
INSERT INTO "clients_positions" VALUES(184,'младший фармацевт','3.6');
INSERT INTO "clients_positions" VALUES(185,'фасовщик','3.6');
INSERT INTO "clients_positions" VALUES(186,'санитар (мойщик)','3.6');
INSERT INTO "clients_positions" VALUES(187,'Биолог','0.4');
INSERT INTO "clients_positions" VALUES(188,'Зоолог','0.4');
INSERT INTO "clients_positions" VALUES(189,'Инженер по техническим средствам реабилитации инвалидов','0.4');
INSERT INTO "clients_positions" VALUES(190,'Инструктор-методист по лечебной физкультуре','0.4');
INSERT INTO "clients_positions" VALUES(191,'Консультант по профессиональной реабилитации инвалидов','0.4');
INSERT INTO "clients_positions" VALUES(192,'Медицинский психолог','0.4');
INSERT INTO "clients_positions" VALUES(193,'Медицинский физик','0.4');
INSERT INTO "clients_positions" VALUES(194,'Специалист по профессиональной ориентации инвалидов','0.4');
INSERT INTO "clients_positions" VALUES(195,'Специалист по социальной работе','0.4');
INSERT INTO "clients_positions" VALUES(196,'Специалист по физиологии труда','0.4');
INSERT INTO "clients_positions" VALUES(197,'Специалист по эргономике','0.4');
INSERT INTO "clients_positions" VALUES(198,'Судебный эксперт (эксперт-биохимик, эксперт-генетик, эксперт-химик)','0.4');
INSERT INTO "clients_positions" VALUES(199,'Химик-эксперт учреждений здравоохранения','0.4');
INSERT INTO "clients_positions" VALUES(200,'Эксперт-физик по контролю за источниками ионизирующих и неионизирующих излучений','0.4');
INSERT INTO "clients_positions" VALUES(201,'Эмбриолог','0.4');
INSERT INTO "clients_positions" VALUES(202,'Энтомолог','0.4');
INSERT INTO "clients_positions" VALUES(203,'Инструктор по трудовой терапии','0.5');
INSERT INTO "clients_positions" VALUES(204,'Инструктор производственного обучения рабочих массовых профессий','0.5');
INSERT INTO "clients_positions" VALUES(205,'Социальный работник','0.5');
INSERT INTO "clients_positions" VALUES(206,'Техник по техническим средствам реабилитации инвалидов','0.5');
