# Generated by Django 3.2.7 on 2021-09-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('fileseq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.fileseq', verbose_name='Файлы')),
                ('place', models.CharField(db_index=True, max_length=24, verbose_name='Объект')),
                ('subject', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Подобъект')),
                ('depart', models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='Направление')),
                ('payer', models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='Плательщик')),
                ('supplier', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Продавец')),
                ('no', models.CharField(db_index=True, max_length=32, verbose_name='Номер')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('sum', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=11, null=True, verbose_name='Сумма')),
                ('events', models.TextField(blank=True, null=True, verbose_name='История')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.org', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Скан',
                'verbose_name_plural': 'Сканы',
                'ordering': ('fileseq',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.CharField(db_index=True, max_length=64, verbose_name='Подписант')),
                ('resume', models.BooleanField(db_index=True, verbose_name='Резолюция')),
                ('ctime', models.DateTimeField(db_index=True, verbose_name='ДатаВремя')),
                ('comment', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Камменты')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invarch.scan', verbose_name='Скан')),
            ],
            options={
                'verbose_name': 'Резолюция',
                'verbose_name_plural': 'Резолюции',
                'ordering': ('ctime',),
            },
        ),
    ]
