BEGIN;
DELETE FROM gw_addrshort;
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (2, "Аобл", "Автономная область");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (3, "Респ", "Республика");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (4, "г", "Город");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (5, "край", "Край");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (6, "обл", "Область");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (7, "округ", "Округ");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (8, "кожуун", "Кожуун");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (9, "р-н", "Район");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (10, "тер", "Территория");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (11, "у", "Улус");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (12, "волость", "Волость");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (13, "дп", "Дачный поселок");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (14, "кп", "Курортный поселок");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (15, "п/о", "Почтовое отделение");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (16, "пгт", "Поселок городского типа");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (17, "рп", "Рабочий поселок");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (18, "с/а", "Сельская администрация");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (19, "с/мо", "Сельское муниципальное образо");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (20, "с/о", "Сельский округ");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (21, "с/п", "Сельское поселение");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (22, "с/с", "Сельсовет");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (23, "сумон", "Сумон");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (24, "аал", "Аал");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (25, "арбан", "Арбан");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (26, "аул", "Аул");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (27, "высел", "Выселки(ок)");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (28, "городок", "Городок");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (29, "д", "Деревня");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (30, "ж/д_будка", "Железнодорожная будка");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (31, "ж/д_казарм", "Железнодорожная казарма");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (32, "ж/д_оп", "ж/д останов. (обгонный) пункт");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (33, "ж/д_платф", "Железнодорожная платформа");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (34, "ж/д_пост", "Железнодорожный пост");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (35, "ж/д_рзд", "Железнодорожный разъезд");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (36, "ж/д_ст", "Железнодорожная станция");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (37, "заимка", "Заимка");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (38, "казарма", "Казарма");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (39, "кв-л", "Квартал");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (40, "кордон", "Кордон");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (41, "лпх", "Леспромхоз");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (42, "м", "Местечко");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (43, "мкр", "Микрорайон");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (44, "нп", "Населенный пункт");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (45, "остров", "Остров");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (46, "п", "Поселок");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (47, "п/р", "Планировочный район");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (48, "п/ст", "Поселок и(при) станция(и)");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (49, "погост", "Погост");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (50, "починок", "Починок");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (51, "промзона", "Промышленная зона");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (52, "рзд", "Разъезд");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (53, "с", "Село");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (54, "сл", "Слобода");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (55, "снт", "Садовое неком-е товарищество");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (56, "ст", "Станция");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (57, "ст-ца", "Станица");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (58, "х", "Хутор");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (59, "аллея", "Аллея");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (60, "б-р", "Бульвар");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (61, "вал", "Вал");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (62, "въезд", "Въезд");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (63, "гск", "Гаражно-строительный кооперат");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (64, "дор", "Дорога");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (65, "жт", "Животноводческая точка");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (66, "заезд", "Заезд");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (67, "канал", "Канал");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (68, "км", "Километр");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (69, "кольцо", "Кольцо");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (70, "коса", "Коса");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (71, "линия", "Линия");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (72, "мост", "Мост");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (73, "наб", "Набережная");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (74, "парк", "Парк");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (75, "пер", "Переулок");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (76, "переезд", "Переезд");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (77, "пл", "Площадь");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (78, "пл-ка", "Площадка");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (79, "платф", "Платформа");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (80, "полустанок", "Полустанок");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (81, "пр-кт", "Проспект");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (82, "проезд", "Проезд");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (83, "просек", "Просек");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (84, "проселок", "Проселок");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (85, "проток", "Проток");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (86, "проулок", "Проулок");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (87, "сад", "Сад");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (88, "сквер", "Сквер");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (89, "спуск", "Спуск");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (90, "стр", "Строение");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (91, "тракт", "Тракт");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (92, "туп", "Тупик");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (93, "ул", "Улица");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (94, "уч-к", "Участок");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (95, "ферма", "Ферма");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (96, "ш", "Шоссе");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (97, "ДОМ", "Дом");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (98, "ряды", "Ряды");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (99, "автодорога", "Автодорога");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (100, "а/я", "Абонентский ящик");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (101, "массив", "Массив");
INSERT INTO gw_addrshort (id, shortname, fullname) VALUES (102, "жилрайон", "Жилой район");
COMMIT;
