# Generated by Django 3.2.7 on 2021-09-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='#')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='#')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Плательщик',
                'verbose_name_plural': 'Плательщики',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=24, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='#')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='#')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Наименование')),
                ('color', models.CharField(db_index=True, max_length=16, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='Наименование')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='contrib.place', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'ПодОбъект',
                'verbose_name_plural': 'ПодОбъект',
                'ordering': ('place', 'id'),
                'unique_together': {('place', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='Пользователь')),
                ('jobtit', models.CharField(db_index=True, max_length=32, verbose_name='Должность')),
                ('canadd', models.BooleanField(db_index=True, verbose_name='Может создавать')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrib.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Подписант',
                'verbose_name_plural': 'Подписанты',
                'ordering': ('role', 'user'),
                'unique_together': {('role', 'user')},
            },
        ),
    ]
