#!/bin/sh
# script to maintain django project

RETVAL=0

MGR="./manage.py"
#DB=`python -c "import settings; print settings.DATABASES['default'];"`
DBNAME=`python -c "import settings; print settings.DATABASES['default']['NAME'];"`
DBUSER=`python -c "import settings; print settings.DATABASES['default']['USER'];"`
DBPASS=`python -c "import settings; print settings.DATABASES['default']['PASSWORD'];"`

case "$1" in
cleanpyc)
	find . -type f -name "*.pyc" -delete
	;;
tables)		# show all tables
	echo "SHOW TABLES;" | $MGR dbshell | grep -v Tables
	;;
dump_old)	# dump whole sql db (old way)
	mysqldump --user=$DBUSER --password=$DBPASS -c --compact -e --skip-opt -t $DBNAME | gzip > $DBNAME.`date +%y%m%d%H%M%S`.sql.gz
	;;
dump)		# dump whole sql db in right order (new way)
	(for i in `cat tables.lst`; do mysqldump --user=$DBUSER --password=$DBPASS -c --compact -e --skip-opt -t $DBNAME $i; done) | gzip > $DBNAME.`date +%y%m%d%H%M%S`.sql.gz
	;;
drop_old)	# drop all SQL tables (old way)
	(echo "BEGIN; SET FOREIGN_KEY_CHECKS=0;" && (echo "SHOW TABLES;" | $MGR dbshell | grep -v Tables | while read i; do echo "DROP TABLE $i;"; done) && echo "COMMIT;") | $MGR dbshell
	;;
drop)		# drop all SQL tables in right order
	(echo "BEGIN; SET FOREIGN_KEY_CHECKS=0;" && (for i in `tac tables.lst | grep -v ^#`; do echo "DROP TABLE $i;"; done) && echo "COMMIT;") | $MGR dbshell
	;;
sync)		# [re]create DB structure
	echo "no" | $MGR migrate
	;;
clean_old)	# delete all records from all tables (old way)
	(echo "BEGIN;" && (echo "SHOW TABLES;" | $MGR dbshell | grep -v Tables | while read i; do echo "DELETE FROM $i;"; done) && echo "COMMIT;") | $MGR dbshell
	;;
clean)		# delete all records from all tables in right order
	(echo "BEGIN; SET FOREIGN_KEY_CHECKS=0;" && (for i in `tac tables.lst`; do echo "DELETE FROM $i;"; done) && echo "COMMIT;") | $MGR dbshell
	;;
restore)	# restore db from gziped sql
	(echo "BEGIN; SET FOREIGN_KEY_CHECKS=0;" && gunzip -c $2 && echo "SET FOREIGN_KEY_CHECKS=1; COMMIT;") | $MGR dbshell
	;;
chk)		# chk db
	(echo "BEGIN;" && (echo "SHOW TABLES;" | $MGR dbshell | grep -v Tables | while read i; do echo "ALTER TABLE $i DISCARD TABLESPACE; ALTER TABLE $i IMPORT TABLESPACE;"; done) && echo "COMMIT;") | $MGR dbshell
	;;
help)
	echo "Das ist help"
	;;
*)
	echo $"Usage: $0 {cleanpyc|dump|drop|sync|clean|restore|help}"
	RETVAL=1
esac

exit $RETVAL
