# Generated by Django 3.2.7 on 2021-09-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrarch',
            fields=[
                ('fileseq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.fileseq', verbose_name='Файлы')),
                ('place', models.CharField(db_index=True, max_length=24, verbose_name='Объект')),
                ('subject', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Подобъект')),
                ('customer', models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='Заказчик')),
                ('depart', models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='Направление')),
                ('payer', models.CharField(db_index=True, max_length=16, verbose_name='Плательщик')),
                ('docno', models.CharField(db_index=True, max_length=32, verbose_name='Номер')),
                ('docdate', models.DateField(db_index=True, verbose_name='Дата')),
                ('docsum', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=11, null=True, verbose_name='Сумма')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.org', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
                'ordering': ('fileseq',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(db_index=True, verbose_name='ДатаВремя')),
                ('approve', models.CharField(db_index=True, max_length=64, verbose_name='Подписант')),
                ('comment', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Замечание')),
                ('contrarch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrarch.contrarch', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Резолюция',
                'verbose_name_plural': 'Резолюции',
                'ordering': ('ctime',),
            },
        ),
    ]
