INSERT INTO dox_ssrf (id, name) VALUES (1, 'Республика Адыгея (Адыгея)');
INSERT INTO dox_ssrf (id, name) VALUES (2, 'Республика Башкортостан');
INSERT INTO dox_ssrf (id, name) VALUES (3, 'Республика Бурятия');
INSERT INTO dox_ssrf (id, name) VALUES (4, 'Республика Алтай');
INSERT INTO dox_ssrf (id, name) VALUES (5, 'Республика Дагестан');
INSERT INTO dox_ssrf (id, name) VALUES (6, 'Республика Ингушетия');
INSERT INTO dox_ssrf (id, name) VALUES (7, 'Кабардино-Балкарская Республика');
INSERT INTO dox_ssrf (id, name) VALUES (8, 'Республика Калмыкия');
INSERT INTO dox_ssrf (id, name) VALUES (9, 'Карачаево-Черкесская Республика');
INSERT INTO dox_ssrf (id, name) VALUES (10, 'Республика Карелия');
INSERT INTO dox_ssrf (id, name) VALUES (11, 'Республика Коми');
INSERT INTO dox_ssrf (id, name) VALUES (12, 'Республика Марий Эл');
INSERT INTO dox_ssrf (id, name) VALUES (13, 'Республика Мордовия');
INSERT INTO dox_ssrf (id, name) VALUES (14, 'Республика Саха (Якутия)');
INSERT INTO dox_ssrf (id, name) VALUES (15, 'Республика Северная Осетия - Алания');
INSERT INTO dox_ssrf (id, name) VALUES (16, 'Республика Татарстан (Татарстан)');
INSERT INTO dox_ssrf (id, name) VALUES (17, 'Республика Тыва');
INSERT INTO dox_ssrf (id, name) VALUES (18, 'Удмуртская Республика');
INSERT INTO dox_ssrf (id, name) VALUES (19, 'Республика Хакасия');
INSERT INTO dox_ssrf (id, name) VALUES (20, 'Чеченская Республика');
INSERT INTO dox_ssrf (id, name) VALUES (21, 'Чувашская Республика - Чувашия');
INSERT INTO dox_ssrf (id, name) VALUES (22, 'Алтайский край');
INSERT INTO dox_ssrf (id, name) VALUES (23, 'Краснодарский край');
INSERT INTO dox_ssrf (id, name) VALUES (24, 'Красноярский край');
INSERT INTO dox_ssrf (id, name) VALUES (25, 'Приморский край');
INSERT INTO dox_ssrf (id, name) VALUES (26, 'Ставропольский край');
INSERT INTO dox_ssrf (id, name) VALUES (27, 'Хабаровский край');
INSERT INTO dox_ssrf (id, name) VALUES (28, 'Амурская область');
INSERT INTO dox_ssrf (id, name) VALUES (29, 'Архангельская область');
INSERT INTO dox_ssrf (id, name) VALUES (30, 'Астраханская область');
INSERT INTO dox_ssrf (id, name) VALUES (31, 'Белгородская область');
INSERT INTO dox_ssrf (id, name) VALUES (32, 'Брянская область');
INSERT INTO dox_ssrf (id, name) VALUES (33, 'Владимирская область');
INSERT INTO dox_ssrf (id, name) VALUES (34, 'Волгоградская область');
INSERT INTO dox_ssrf (id, name) VALUES (35, 'Вологодская область');
INSERT INTO dox_ssrf (id, name) VALUES (36, 'Воронежская область');
INSERT INTO dox_ssrf (id, name) VALUES (37, 'Ивановская область');
INSERT INTO dox_ssrf (id, name) VALUES (38, 'Иркутская область');
INSERT INTO dox_ssrf (id, name) VALUES (39, 'Калининградская область');
INSERT INTO dox_ssrf (id, name) VALUES (40, 'Калужская область');
INSERT INTO dox_ssrf (id, name) VALUES (41, 'Камчатский край');
INSERT INTO dox_ssrf (id, name) VALUES (42, 'Кемеровская область');
INSERT INTO dox_ssrf (id, name) VALUES (43, 'Кировская область');
INSERT INTO dox_ssrf (id, name) VALUES (44, 'Костромская область');
INSERT INTO dox_ssrf (id, name) VALUES (45, 'Курганская область');
INSERT INTO dox_ssrf (id, name) VALUES (46, 'Курская область');
INSERT INTO dox_ssrf (id, name) VALUES (47, 'Ленинградская область');
INSERT INTO dox_ssrf (id, name) VALUES (48, 'Липецкая область');
INSERT INTO dox_ssrf (id, name) VALUES (49, 'Магаданская область');
INSERT INTO dox_ssrf (id, name) VALUES (50, 'Московская область');
INSERT INTO dox_ssrf (id, name) VALUES (51, 'Мурманская область');
INSERT INTO dox_ssrf (id, name) VALUES (52, 'Нижегородская область');
INSERT INTO dox_ssrf (id, name) VALUES (53, 'Новгородская область');
INSERT INTO dox_ssrf (id, name) VALUES (54, 'Новосибирская область');
INSERT INTO dox_ssrf (id, name) VALUES (55, 'Омская область');
INSERT INTO dox_ssrf (id, name) VALUES (56, 'Оренбургская область');
INSERT INTO dox_ssrf (id, name) VALUES (57, 'Орловская область');
INSERT INTO dox_ssrf (id, name) VALUES (58, 'Пензенская область');
INSERT INTO dox_ssrf (id, name) VALUES (59, 'Пермский край');
INSERT INTO dox_ssrf (id, name) VALUES (60, 'Псковская область');
INSERT INTO dox_ssrf (id, name) VALUES (61, 'Ростовская область');
INSERT INTO dox_ssrf (id, name) VALUES (62, 'Рязанская область');
INSERT INTO dox_ssrf (id, name) VALUES (63, 'Самарская область');
INSERT INTO dox_ssrf (id, name) VALUES (64, 'Саратовская область');
INSERT INTO dox_ssrf (id, name) VALUES (65, 'Сахалинская область');
INSERT INTO dox_ssrf (id, name) VALUES (66, 'Свердловская область');
INSERT INTO dox_ssrf (id, name) VALUES (67, 'Смоленская область');
INSERT INTO dox_ssrf (id, name) VALUES (68, 'Тамбовская область');
INSERT INTO dox_ssrf (id, name) VALUES (69, 'Тверская область');
INSERT INTO dox_ssrf (id, name) VALUES (70, 'Томская область');
INSERT INTO dox_ssrf (id, name) VALUES (71, 'Тульская область');
INSERT INTO dox_ssrf (id, name) VALUES (72, 'Тюменская область');
INSERT INTO dox_ssrf (id, name) VALUES (73, 'Ульяновская область');
INSERT INTO dox_ssrf (id, name) VALUES (74, 'Челябинская область');
INSERT INTO dox_ssrf (id, name) VALUES (75, 'Забайкальский край');
INSERT INTO dox_ssrf (id, name) VALUES (76, 'Ярославская область');
INSERT INTO dox_ssrf (id, name) VALUES (77, 'г.Москва');
INSERT INTO dox_ssrf (id, name) VALUES (78, 'г.Санкт-Петербург');
INSERT INTO dox_ssrf (id, name) VALUES (79, 'Еврейская автономная область');
INSERT INTO dox_ssrf (id, name) VALUES (83, 'Ненецкий автономный округ');
INSERT INTO dox_ssrf (id, name) VALUES (86, 'Ханты-Мансийский автономный округ - Югра');
INSERT INTO dox_ssrf (id, name) VALUES (87, 'Чукотский автономный округ');
INSERT INTO dox_ssrf (id, name) VALUES (89, 'Ямало-Ненецкий автономный округ');
INSERT INTO dox_ssrf (id, name) VALUES (99, 'Иные территории,включая город и космодром Байконур');
